In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import tensorflow

In [3]:
import numpy as np

In [8]:
a = np.array([[0.4707, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5085, 0.0000, 0.0000, 0.0000, 0.0000]])

In [12]:
a[[1,0,2,1],2]

array([0., 0., 0., 0.])

In [14]:
a[[1],[2]]

array([0.])

In [18]:
a[[1]] = [3,4,5,6,7
         ]

In [26]:
a.ndim != 2

False

In [40]:
c = np.array([1,0,2,1])

In [41]:
a[[1,0,2,1]]

array([[3.    , 4.    , 5.    , 6.    , 7.    ],
       [0.4707, 0.    , 0.    , 0.    , 0.    ],
       [0.5085, 0.    , 0.    , 0.    , 0.    ],
       [3.    , 4.    , 5.    , 6.    , 7.    ]])

In [42]:
a[c]

array([[3.    , 4.    , 5.    , 6.    , 7.    ],
       [0.4707, 0.    , 0.    , 0.    , 0.    ],
       [0.5085, 0.    , 0.    , 0.    , 0.    ],
       [3.    , 4.    , 5.    , 6.    , 7.    ]])

In [59]:
b = np.array([3,4,5,6,7], dtype = 'int16')

In [60]:
tuple(b)

(3, 4, 5, 6, 7)

In [61]:
a[tuple(np.array([1,0]))]

3.0

In [94]:
a[tuple(np.array([1]))]

array([3., 4., 5., 6., 7.])

In [62]:
a[np.array([1,0])]

array([[3.    , 4.    , 5.    , 6.    , 7.    ],
       [0.4707, 0.    , 0.    , 0.    , 0.    ]])

In [95]:
a[np.array([1])]

array([[3., 4., 5., 6., 7.]])

In [63]:
b.max()

7

In [64]:
b.tolist()

[3, 4, 5, 6, 7]

In [65]:
a.max()

7.0

In [29]:
range(3)
np.zeros(range(3))

array([], shape=(0, 1, 2), dtype=float64)

In [27]:
np.zeros(3)

array([0., 0., 0.])

In [67]:
b.dtype == 'int16'

True

In [50]:
e = (6,7)
f = (8,9)
g=np.zeros(e + (len(f),))


In [52]:
True or False

True

In [54]:
len([2,"3"])

2

In [68]:
max((2,3))

3

In [84]:
h = np.array([4,5,6,7,8])

In [81]:
w = h[tuple(np.array([4,5]))]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [92]:
q = getPick(np.array([4,3]))

In [88]:
h.shape[0]

5

In [93]:
q(h)

array([8, 7], dtype=int16)

In [96]:
np.array([[1],[2]], dtype = 'int16')

array([[1],
       [2]], dtype=int16)

In [89]:
def getPick(p):
    if p.ndim != 1:
        raise Exception("ndim does not equal 1！");
    lp = p.shape[0]
    mx = p.max();
    mn = p.min();
    def pick(i):
        if i.ndim != 1:
            raise Exception("ndim does not equal 1！");        
        lt = i.shape[0];
        if lt <= mx:
            raise Exception("Argument Invalid！");
        j = np.zeros(lp, dtype = 'int16');
        for k in range(lp):
            j[k]= i[p[k]];
        return j
    return pick

In [99]:
IC = np.array([3,4,0,1,5,6,7], dtype = 'int16');
E = np.array([[[1,0],[1,0]],[[1,0],[0,1]]], dtype = 'int16');
pick = getPick(np.array([2,3], dtype = 'int16'));
J = pick(IC)
E[tuple(J)]


array([1, 0], dtype=int16)

In [100]:
list((2,3))

[2, 3]

In [ ]:
def combine(pk0, pk1, pk):
    IC = np.array([1,2,3,4,5,6,7], dtype = 'int16')
    E = np.array([[1],[0]], dtype = 'int16')
    pick0 = getPick(p0);
    pick1 = getPick(p1);
    pick = getPick(p0);

In [104]:
def getProvisionXTransformer(shape0, shape1, T0, p0, p1, p):    
    if p0.dtype != 'int16' or p0.dtype != 'int16' or p.dtype != 'int16':
        raise Exception("Data type error！");
    elif p0.ndim != 1 or p0.ndim != 1 or p.ndim != 1:
        raise Exception("ndim to form pick does not equal 1！");
    E = np.zeros(shape0 + (len(shape1),), dtype = 'int16');
    I = np.zeros(len(shape0), dtype = 'int16');
    J = np.zeros(len(shape1), dtype = 'int16');
    pick0 = getPick(p0);
    pick1 = getPick(p1);
    pick = getPick(p0);
    def combine(IC):
        Jp0 = pick(IC);
        Jp = T0[tuple(Jp0)]
        J0 = pick0(IC)
        J1 = pick1(IC)
        Jl = list(tuple(Jp) + tuple(J0))
        Ja = np.array(Jl, dtype = 'int16')
        Jout = pick(Ja)
        return Jout
    for i in range(len(shape0)):
        ni = shape0[i];
        for j in range(ni):
            I[i] = j;
            if i == ni - 1:
                J = combine(I);
                E[I] = J;
    return E

In [108]:
z = (6,5,7,8,9)
z[0:]

(6, 5, 7, 8, 9)

In [ ]:
def scatterX(src, X, shape1, T0, p0, p1, p):
    shape0 = X.shape[:-1];
    XTransformer = getProvisionXTransformer(shape0, shape1, T0, p0, p1, p);
    I = np.zeros(len(shape0), dtype = 'int16');
    for i in range(len(shape0)):
        ni = shape0[i];
        for j in range(ni):
            I[i] = j;
    src[tuple(I)] = X[tuple(XTransformer[tuple(I)])]
    return src
