In [1]:
import tensorflow as tf
import numpy as np

In [2]:
import ScatterX as x

In [3]:
def tensorflowScatter(tensor, indices, updates):
    l = list(range(len(indices.shape) - 1))
    tl = indices.shape[-1]
    ln = list(range(len(tensor.shape)))
    t1 = ln[tl:]   
    p0 = np.array(l, dtype='int16')
    p1 = np.array(t1, dtype='int16')
    p = np.array(ln, dtype='int16')
    x.scatterX(tensor, updates, indices, p0, p1, p)

In [13]:
#test case 0 tf
indices = tf.constant([[2], [3], [5], [4]])
updates = tf.constant([6, 9, 22, 88])
tensor = tf.ones([10], dtype=tf.int32)
s = tf.tensor_scatter_nd_update(tensor, indices, updates)
print(s.numpy())

[ 1  1  6  9 88 22  1  1  1  1]


In [14]:
#test case 0
tensor0 = np.ones([10], dtype='int16')
indices = np.array([[2], [3], [5], [4]], dtype='int16')
updates = np.array([6, 9, 22, 88], dtype='int16')
tensorflowScatter(tensor0, indices, updates)
tensor0

array([ 1,  1,  6,  9, 88, 22,  1,  1,  1,  1], dtype=int16)

In [11]:
#test case 1
indices = tf.constant([[0], [3]])
updates = tf.constant([[[2,4,3,7], [1, 6,1, 6],
                        [4,5,6,7], [9,0,0,0]],
                       [[8, 8, 8, 5], [7, 6, 7, 6],
                        [9, 1, 7, 1], [1, 3, 7, 5]]])

tensor = tf.ones([4, 4, 4], dtype = tf.int32)

print(tf.tensor_scatter_nd_update(tensor, indices, updates).numpy())

[[[2 4 3 7]
  [1 6 1 6]
  [4 5 6 7]
  [9 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[8 8 8 5]
  [7 6 7 6]
  [9 1 7 1]
  [1 3 7 5]]]


In [12]:
#test case 1
indices = np.array([[0], [2]], dtype='int16')
updates = np.array([[[2,4,3,7], [1, 6,1, 6],
                        [4,5,6,7], [9,0,0,0]],
                       [[8, 8, 8, 5], [7, 6, 7, 6],
                        [9, 1, 7, 1], [1, 3, 7, 5]]], 
                      dtype='int16')
tensor = np.ones([4, 4, 4], dtype='int16')
tensorflowScatter(tensor, indices, updates)
tensor

array([[[2, 4, 3, 7],
        [1, 6, 1, 6],
        [4, 5, 6, 7],
        [9, 0, 0, 0]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[8, 8, 8, 5],
        [7, 6, 7, 6],
        [9, 1, 7, 1],
        [1, 3, 7, 5]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [9]:
tf.version.VERSION

'2.3.1'